# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TripInformation.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "wheelypb.Point" do
    optional :lat, :double, 1
    optional :long, :double, 2
  end
  add_message "wheelypb.Trip" do
    optional :start, :message, 1, "wheelypb.Point"
    optional :end, :message, 2, "wheelypb.Point"
  end
  add_message "wheelypb.TripInformationResponse" do
    optional :distance, :int64, 1
    optional :time, :int64, 2
  end
end

module Wheelypb
  Point = Google::Protobuf::DescriptorPool.generated_pool.lookup("wheelypb.Point").msgclass
  Trip = Google::Protobuf::DescriptorPool.generated_pool.lookup("wheelypb.Trip").msgclass
  TripInformationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("wheelypb.TripInformationResponse").msgclass
end
