# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: TripInformation.proto for package 'wheelypb'

require 'grpc'
require 'TripInformation_pb'

module Wheelypb
  module TripInformation
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'wheelypb.TripInformation'

      rpc :GetTripInformation, Trip, TripInformationResponse
    end

    Stub = Service.rpc_stub_class
  end
end
